name: fragmenter
channels:
  - conda-forge

dependencies:

  # Base depends
  - python
  - setuptools

  # Sphinx specific
  - nbsphinx
  - nbsphinx-link
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pandoc
  - ipython

    # Standard dependencies
  - numpy
  - pydantic
  - pyyaml
  - networkx
  - jinja2

  - pip:
      - autodoc_pydantic==1.1.3
