name: lint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only openff/fragmenter

      - name: Run black
        run: |
          black openff/fragmenter --check

      - name: Run flake8
        run: |
          flake8 openff/fragmenter
