name: lint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: "0 0 * * *"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.7'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only fragmenter

      - name: Run black
        run: |
          black fragmenter --check

      - name: Run flake8
        run: |
          flake8 fragmenter
